spring:
  application:
    name: share-study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:23305/share_study?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 26378
    host: xxx.xxx.xxx.xxx
    password: 123456
    database: 0
    jedis:
      pool:
        max-wait: 10ms
        max-active: 8
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000
  rabbitmq:
    host: xxx.xxx.xxx.xxx
    virtual-host: /
    username: admin
    password: admin123456
    port: 25672
    publisher-confirm-type: correlated
    template:
      mandatory: true
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
tencent:
  cos:
    file:
      region: ap-chengdu
      secret-id: xxx
      secret-key: xxx
      bucket-name: sharestudy-xxx